### ISSUE TITLE
reponse to #18

### ISSUE THREAD

**Issue by jczimm** [loverajoel/jstips#104]
made a quick [jsperf](http://jsperf.com/flooring-numbers-comparison)...

In this test, it looks like Math.floor is faster.

**Comment by loverajoel** [comment]
@pklinger ping

**Comment by drakmail** [comment]
Interesting – in safari 9 performance of `Math.floor()` is really ugly, but in Chrome it is fasted method :)

**Comment by drakmail** [comment]
Added firefox tests – performance of all this methods is same in it

**Comment by pklinger** [comment]
huh interesting. have a look at #85 and the [link with past performances](https://github.com/loverajoel/jstips/pull/85#issuecomment-172122884). I only tested it with Chrome

**Comment by rjgotten** [comment]
@jczimm 
@pklinger

> made a quick jsperf...

FYI: That test is no good.

Engines may memoize the results of a function when static code analysis shows that it is side-effect free and has deterministic output and when the same input is repeatedly fed into the function. That is exactly the case here: the test uses a single constant, picked before the clocked test loops, and the function under test produces deterministic results.

At the very least use a test that employs a function with side-effects. For instance; prepopulate an array of floating point numbers, where each value, when truncated to an integer, would point to the next index to pick from the array in a next iteration of the test.

However, you really should stop putting stock into micro-benchmarks like this altogether, because they've been proven time and again _TO - NOT - WORK_ with modern JS runtimes.

**Comment by jczimm** [comment]
[updated jsperf with @rjgotten 's suggestion](http://jsperf.com/flooring-numbers-comparison/2)

Alright, looks about the same for all three methods.
