### ISSUE TITLE
#18 Title says rounding, but the code truncate.

### ISSUE THREAD

**Issue by malexandre** [loverajoel/jstips#114]
For example, this line:

``` js
console.log(~~1.999); // 1
```

Rounding 1.999 should give 2, not 1. 1 is either flooring or truncating. And as the example shows that negative values are like `Math.ceil`, it means `~~` is only truncating.

Also, on another note, truncating could be done using `parseInt`, which is the cleaner way I think.

**Comment by loverajoel** [comment]
@gogainda ping

**Comment by loverajoel** [comment]
@pklinger ping

**Comment by rjgotten** [comment]
> Also, on another note, truncating could be done using parseInt, which is the cleaner way I think.

No it's not. You run afoul of number vs. string representations, radix handling, etc.

The cleanest way to truncate a number is to [use the standard Math.trunc function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc), or polyfill it with the suggested implementation from Mozilla...

**Comment by malexandre** [comment]
My bad, I forgot to check the Math functions, and just used my C habits (casting to int).

**Comment by pklinger** [comment]
@malexandre Ok, "rounding" is definitively wrong in the mathematical sense. What it really does is truncating and mimicing as explained in the text:

> making it a great tool to round towards 0. For numeric input, it therefore mimics the Math.ceil() for negative and Math.floor() for positive input

In the end, I guess people want to see some unknown, (more or less) useful tricks here. Not being 100% accurate on the title to have a use case, but brining across a new trick was my main intention here.
If you feel really disturbed by the title, issue a PR and correct it 'mathematically correct', yet exciting. I'm happy to see improvements, really.
Also,

```
console.log(~~(2147483647 + 1) === (2147483647 + 1)) // -> 0
```

needs a makeover saying `false` instead of `0` as it is comparing.
