### ISSUE TITLE
Consider using form submissions

### ISSUE THREAD

**Issue by mallowigi** [loverajoel/jstips#12]
This repository is not really suited for pull requests: there is only one file to edit and we don't exactly know how. Why not use forms to let people post their tips, then select one every day?

**Comment by loverajoel** [comment]
hey @mallowigi,
I thought create a form or even a blog, but developers likes use github and write markdown, that's the reason why I chose this.
In order to add a new tip is easily. Just add your tip with [this format](https://github.com/loverajoel/jstips/blob/master/CONTRIBUTING.md#tip-format) at the top of the [tips list](https://github.com/loverajoel/jstips#tips-list).
Why do you think that isn't clear?

Thanks for your suggestion

**Comment by loverajoel** [comment]
close by inactivity
