### ISSUE TITLE
One tip per file

### ISSUE THREAD

**Issue by eggcaker** [loverajoel/jstips#13]
How about keep one tip per file instead one page for all ?
In the future can do view tips like tldr ?  can generate the  one page tips with each tip .

**Comment by loverajoel** [comment]
Hey @eggcaker, yes, this is a good idea, I know that when the list of tips will grow up will be difficult to read.
I like the idea of all tips in the same file, because it's easy to read, but yes maybe the `readme` can be a index and each tip in separate files.

I think that the files should be named `#N - title` -> `01 - AngularJs: $digest vs $apply`

**Comment by eggcaker** [comment]
kind of， like a blog entry `#date #N #tags title` more for seach and read in the future.

**Comment by primozs** [comment]
Maybe post on a static site with rss.

**Comment by macx** [comment]
@primozs +1

**Comment by loverajoel** [comment]
I'm thinking use [jekyll-now](https://github.com/barryclark/jekyll-now) when the amount of tips grow

**Comment by eknowles** [comment]
Can I suggest using Wintersmith? https://github.com/jnordberg/wintersmith

If you've used jekyll it'll be very familiar. We can have a script that auto populates the author, contributors and have the build files on the gh-pages branch.

**Comment by loverajoel** [comment]
@eknowles sure I will try it, thanks

**Comment by cgmartin** [comment]
Since on the topic of static generators, a good leaderboard of the top open-source projects to choose from (can filter by JS) https://www.staticgen.com/

**Comment by mallowigi** [comment]
+1

**Comment by hemanth** [comment]
You could use `doxie`, like what [git-tips](https://github.com/git-tips/tips) does.

**Comment by pklinger** [comment]
I also want to throw in, that using resources like images could be nice for some tips. Therefore, a nested folder structure could be useful for the future. At the moment, the project structure would be messed up pretty quickly if somebody wants to use image assets. Also, the loading speed of the single-page readme approach does not scale too well ...

**Comment by hueitan** [comment]
jstips(current/free way) can give more details on the section.
doxie is given only predefined structure.

**Comment by drakmail** [comment]
:+1: for one tip per file

**Comment by pmuens** [comment]
:+1: Really like the RSS idea. So that one can subscribe to the feed and get a new tip delivered every day!

**Comment by drakmail** [comment]
@pmuens also, you can subscribe to [email subscription](http://js2016.tips) or [use auto generated RSS feed](http://us12.campaign-archive2.com/feed?u=91c81a54b7387a056b046a2ca&id=9551be788c) (can be rendered with issues in some RSS clients)

**Comment by tylerdmace** [comment]
+1 The sooner this gets implemented, the better!

**Comment by AdriVanHoudt** [comment]
I liked how I could read through them, for the repo 1/file makes sense but then a website or something where they get bundled would be needed

**Comment by drakmail** [comment]
It not so hard just use something like Jekyll to convert it to nice blog format :)

Btw I'm planning to setup jekyll on js2016.tips website

**Comment by pmuens** [comment]
@drakmail thanks for the links!

**Comment by mrosata** [comment]
I like the 1 tip idea. What about using https://readthedocs.org/ - I love how people write on Github, and I think it's smart because it allows comments and easy updating. With "read the docs" the files could still be hosted here but as the text grows it would also be organized, navigable and I don't know too much about "read the docs" but I know they use make to build the documentation so maybe that could be extended to output a single .md as well. Get the best of both worlds?

**Comment by loverajoel** [comment]
Hi guys, I'm working in the theme for jekyll in this [branch](https://github.com/loverajoel/jstips/tree/gh-pages) and the beta is live in [tipsjs.co](http://www.jstips.co/).
After debug and review the site I have in mind change the branch `gh-page` how `master` of this repo.
Now there are one tip per file and a TOP in the readme.

Feedback are welcome!
