### ISSUE TITLE
Should framework tips be included?

### ISSUE THREAD

**Issue by tevko** [loverajoel/jstips#18]
Hey, thanks for making this awesome project! I'm wondering if framework specific tips should be included? Including these might make more difficult for beginners to understand, not to mention harder to maintain, since frameworks update, get rewritten, and become anti-patterns rather quickly. 

Alternatively, allowing only vanilla javascript content will better serve beginners looking to understand language fundamentals, while promoting a better understanding of the language that so many frameworks and libraries depend on.

**Comment by aglipanci** [comment]
:+1: totally agree with @tevko

**Comment by loverajoel** [comment]
Hey @tevko thanks for your suggestion!

I'm not sure about what you proposed, these are my thoughts:
- Today frameworks are an important part of JS and it's a way to learn the language and best practices.
- JS Tips is not focused on beginners only.
- Share knowledges about famous frameworks will let that beginners know the frameworks/libraries and avoid common mistakes.
- It's hard write 365 tips only for javascript without frameworks, the idea it's include tips about tooling, dev environments, frameworks and more things related

But we can talk about it maybe I'm wrong, and only js is better for the project

**Comment by davecan** [comment]
Hi @loverajoel, thanks for taking the time to start a project like this. These are my opinions but maybe this will contribute to the discussion a bit.

There is merit to both approaches. However, I'll add that it is jarring to come to a project named "Javascript Tips" and see the first tip is about manipulating plain JS arrays followed by a tip about a deep (to me) aspect of Angular, a framework with which I know basically nothing (yet). This followed by a tip on React, again a framework I know nothing about.

So to me that kind of defeats the purpose of a project named "Javascript Tips" because it is neither accessible to newcomers nor is it a useful reference ("cookbook") of actual JS techniques. Because a newcomer will immediately be thrown into the deep end of the pool by seeing Angular as the second tip, and a veteran will have to wade through what is essentially a random collection of tips from what may be such a huge variety of frameworks that it isn't very helpful at all.

Personally I would look for see Angular tips on a page titled "Angular Tips", for React tips on a page titled "React Tips", etc. And I would think a page titled "Javascript Tips" would be designed to help us all become better at _Javascript_ itself. :)

These are just my thoughts, I'm sure others may make better points than me. Maybe have one pure-JS tip each day with one "bonus" tip each day that is about a framework? That way everybody gets the pure-JS tip and can still pick up some tips from other frameworks along the way.

With all that said I think the motivation behind the project is fantastic and would be very helpful to people. So way to go on getting this started, however it turns out. :)

**Comment by tevko** [comment]
@davecan said it better than I could :+1:

**Comment by vishaltelangre** [comment]
:+1:

**Comment by greemwahr** [comment]
+1

**Comment by phil-r** [comment]
:+1:

**Comment by rocketinventor** [comment]
I like the purely Javascript tips because they are useful to all frameworks and all levels.
However, occasional (1 - 2 / week) framework tips are okay if they contribute to better JS mastery.
I like the idea of making the framework tips "bonus", and I also like the daily reading style.
Good work so far!

**Comment by bookercodes** [comment]
I found all the tips _except_ for the Angular and React ones interesting. That's not to say that they're not, it's just that I, too, would prefer to only see vanilla JavaScript tips.

I full well appreciate that writing about vanilla JavaScript only is limiting, but given the immediate success of this repository, I think it's likely that people will submit ideas and, if you're open to it, full-blown tips for consideration.

**Comment by loverajoel** [comment]
ok you convince me, I like the idea about only vanilla JS and how a bonus extra tips(frameworks, devtools, ...)
What about this kind of tips https://github.com/loverajoel/jstips/pull/33? it's node

I will rewrite the rules, thanks all for your suggestions, so helpful!

I'll wait for your proposals tips :smiley_cat:

**Comment by rocketinventor** [comment]
I think a few node tips here and there are okay. Code for node _is_ javascript.

**Comment by aaron-goshine** [comment]
@loverajoel You are doing a great job with jstips, but you should encourage separations of concern anytime there is a need for it, jstips for pure Js pursuers and framework/library tips for frameworkers/librarians; if not then this repo will blow up into a puff of mushroom cloud. In the mean time talking about 365 days of the the year... Is there any one who would like to recommend music tracks or from youtube that are nice to listen while coding javascript or working with frameworks no separation of concern need on this one. https://github.com/aaron-goshine/three-sixtyfive-days-of-rain have a look at what I have so far https://github.com/aaron-goshine/three-sixtyfive-days-of-rain/blob/master/public/js/playlist-recommendation.js pull requests are welcome
